### PR TITLE
Cocoapods and swift 1.1 support

### PR DESCRIPTION
**Pull request by asotog**
Hi there,

Was able to use swift-validator properly in a project, worked great, but wanted  to add it through pods, these pull request lets you use it, configuring the Podfile to something like this (of course after pull request it can be pointed to the main repo)

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.1"
use_frameworks!

pod 'Swift-Validator', :git => 'https://github.com/asotog/swift-validator'
```

Also updated the code to support previous version of swift,  swift 1.2 still beta i think so better to still using previous

Thanks in advance

### CODE REVIEW

**Comment by jpotts18** [comment]
Thanks for the contribution! I have moved swift 1.2 support to a different branch. I'll merge this and maybe you can help me get it into a cocoapod the right way.

**Comment by asotog** [comment]
np, on Podfile you can explicitly point to particular branch, yep swift 1.2 will be released soon
```
pod 'Swift-Validator', :git => 'https://github.com/asotog/swift-validator', :branch => 'swift-1.2'
```

**Comment by jpotts18** [comment]
Okay so I just tried to push a new release 2.0.2 with some new changes and Swift 1.1

I updated my Swift-Validator.podspec and ran ``pod spec lint`` and I am getting this error. 

```
 -> Swift-Validator (2.0.2)
    - ERROR | [iOS] Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [iOS]  Swift-Validator/Validator/EmailRule.swift:24:16: error: 'NSPredicate?' does not have a member named 'evaluateWithObject'
```

```swift
func validate(value: String) -> Bool {
    return NSPredicate(format: "SELF MATCHES %@", self.REGEX).evaluateWithObject(value)
}
```

Any ideas?

**Comment by asotog** [comment]
i think probably because nspredicate could be undefined have to check first like 
```
       if let emailTest = NSPredicate(format: "SELF MATCHES %@", REGEX) {
            if emailTest.evaluateWithObject(value) {
                return true
            } else {
                return false
            }
        }
```

**Comment by asotog** [comment]
i think pod is looking not the pull request version, you have to tag the code first and then use pod spec lint and update the tag number in the spec file

**Comment by asotog** [comment]
also need to add `public` to all classes, initializers, protocols i can work on that, i was trying a clean project using the pod but it complains about will make that change stay tuned

**Pull request merged**
